Skip results where bookname is nil.
This causing an error:

     NoMethodError:
       undefined method `chapters' for nil:NilClass
     # ./lib/bible_bot/parser.rb:173:in `normalize_reference'